version: '3'
services:

  lz:
    image: klakegg/hugo:ext-alpine
    command: server
    volumes:
      - "./lz:/src"
    ports:
      - "1313:1313"

  paper:
    image: klakegg/hugo:ext-alpine
    command: server
    volumes:
      - "./paper:/src"
    ports:
      - "1414:1313"
